### ISSUE TITLE
Cannot find symbol

### ISSUE THREAD

**Issue by gerbil** [tsubik/cordova-plugin-start-on-boot#2]
[javac] ..StartAppAtBootReceiver.java:14: error: cannot find symbol
[javac]             Intent serviceIntent = new Intent(context, com.example.xxx.MainActivity);

Could you please provide example of workign manifest + java file?

**Comment by tsubik** [comment]
It should be something like this `Intent serviceIntent = new Intent(context, PACKAGE_NAME.MainActivity)` where `PACKAGE_NAME` is I believe in cordova `config.xml` as a root widget `id`. Take a look [here](https://github.com/cowbell/ionic-geofence/blob/master/config.xml#L2), for this example `PACKAGE_NAME` is `com.tsubik.ionicgeofence`.

**Comment by tsubik** [comment]
But I need to update this plugin to avoid manual configuration like this.
